name: Actors Player Tests

on:
  push:
    branches:
      - develop
      - feature/**
    paths:
      - 'cabo-client/**'
      - 'cabo-commons/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/actors_player_test.yml'
  pull_request:
    branches:
      - develop
    paths:
      - 'cabo-client/**'
      - 'cabo-commons/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/actors_player_test.yml'

jobs:
  build_and_test_with_single_jvmm:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: "Build and Test Player Client components with Single-JVM"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: "Build: Compile Client and Commons Modules"
        run: sbt "project client" compile

      - name: "Test: Client Actor Logic (ClientTest)"
        run: sbt "project client" "testOnly ClientTest"

      - name: "Test: Game Coordinator Logic (GameCoordinatorActorSpec)"
        run: sbt "project client" "testOnly GameCoordinatorActorSpec"

      - name: "Test: View Command listener (ViewUserCommandListenerSpec)"
        run: sbt "project client" "testOnly ViewUserCommandListenerSpec"

  build_and_test_with_multi_jvm:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: "Build and Test Multi-JVM"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: "Build: Compile Client and Commons Modules"
        run: sbt "project client" compile

      - name: "Test: Multi-JVM Tests for Actor Player (ActorPlayerMultiJvmSpec)"
        run: sbt "project client" "multi-jvm:test"